# Numpy
- Scientific computing in python
- High performance multidimensional array object and tools with these arrays
## Arrays
- A numpy array is a grid of values, **all of the same type**, and is indexed by a tuple of nonnegative integers.
- **Number of the dimension** is the **rank** of the array
- The **shape** of an array is a **tuple of integers** giving the size of the array along each dimensios

In [3]:
import numpy as np
a = np.array([1, 2, 3]) # rank 1 array
print(a.shape) # (3,) -> shape of the array

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"

(3,)
(2, 3)


## Several way to create function in the Numpy

In [8]:
a = np.zeros((4,2))
print((a))

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((4,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.81596886 0.94761992]
 [0.82796732 0.63850915]
 [0.77726637 0.52413783]
 [0.91075518 0.77713821]]


## Array indexing

In [11]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77
